# Generated by Django 2.2.10 on 2020-04-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='school name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='school description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='schools/pictures')),
                ('subjects_offered', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='verified schools are also recognized as an official school.', verbose_name='verified school')),
                ('is_public', models.BooleanField(default=True, help_text='Visible schools are listed in the main page so everyone know about their existence.')),
            ],
            options={
                'ordering': ['-subjects_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
