# Generated by Django 2.2.10 on 2020-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Teachers can upload content such as videos or articles on school courses.', verbose_name='school teacher'),
        ),
    ]
