# Generated by Django 2.2.10 on 2020-05-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200501_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='used_invitations',
        ),
    ]
