# Generated by Django 2.2.10 on 2020-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200420_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='articles_offered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='videos_offered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
